### PR TITLE
Optional add fmt 3rdparty lib

### PR DESCRIPTION
**Pull request by mizinovmv**

### CODE REVIEW

**Comment by hcho3** [comment]
No, fmtlib is essential in codegen. It cannot be made optional.

**Comment by mizinovmv** [comment]
@hcho3 ok, how resolve error with many dependencies with fmt?

CMake Error at libs/<dependency>/libs/fmt/CMakeLists.txt:157 (add_library):
  add_library cannot create target "fmt" because another target with the same
  name already exists.  The existing target is a shared library created in
  source directory
  "github/project/libs/treelite/3rdparty/fmt/fmt".  See
  documentation for policy CMP0002 for more details.

**Comment by hcho3** [comment]
@mizinovmv Are you using Treelite as a submodule to another application? Is your application using fmtlib?

**Comment by mizinovmv** [comment]
@hcho3  yes, treelite as git submodule of project.
Project has many submodules and one of them has fmt dependency too.

project:
-- treelite -> fmt
-- lib2 -> fmt
-- lib3 -> fmt

fmt versions are compatible.

**Comment by hcho3** [comment]
@mizinovmv I see now what you are doing here. Did you run install fmtlib into the system using `make install`? If so, we could use `find_package()` directive to use system fmtlib instead.

**Comment by mizinovmv** [comment]
@hcho3 I dont install system fmtlib.

I want something like this in cmake without any system libs:
In root CMakeLists.txt
set(lib1_FMT ON CACHE BOOL "on fmt")
add_subdirectory(libs/lib1)
set(TREELITE_FMT OFF CACHE BOOL "on fmt")
add_subdirectory(libs/treelite)

I dont know now how make this with find_package :(

**Comment by hcho3** [comment]
We can detect existence of `fmt` CMake target. If the target already exists, then Treelite can use that target again.

**Comment by hcho3** [comment]
@mizinovmv See if the new change works for you.

**Comment by mizinovmv** [comment]
hcho3 yes, resolve problem, thanks!

**Pull request merged**
