### PR TITLE
Implement model concatenation

### LINKED ISSUE #407: Implement model concatenation
It's useful to combine multiple forests into one forest, especially when you fit multiple trees in parallel in a distributed computing environment. RAPIDS's cuML already has its own logic to do this:
https://github.com/rapidsai/cuml/blob/50716cf98c4103aa8dbbcc4ea64897ccb7a70722/cpp/src/randomforest/randomforest.cu#L396

### PR DESCRIPTION
**Pull request by hcho3**
Closes #407

This is a straightforward port of https://github.com/rapidsai/cuml/blob/50716cf98c4103aa8dbbcc4ea64897ccb7a70722/cpp/src/randomforest/randomforest.cu#L396

### CODE REVIEW

**Comment by hcho3** [comment]
@wphicks Can I get a quick review on this one?

**Review by trivialfis — COMMENTED** [review]
Is this for RF or for boosting as well?

**Comment by hcho3** [comment]
@trivialfis This is for any forest type, whether it be RF or boosting.

**Review by wphicks — APPROVED** [review]
Love the implementation, love the feature!

**Pull request merged**
