### PR TITLE
Prepare for a stable 1.0.0 release

### PR DESCRIPTION
**Pull request by hcho3**
* Update dmlc-core submodule to the latest version, to take advantage of various optimizations in the logging facility.
* Lower CMake requirement to 3.13. See #189. The `FetchContent_MakeAvailable` command is only for CMake 3.14+, so define it ourselves when CMake version is 3.13.
* Make static libs (`libtreelite.a`, `libtreelite_runtime.a`) optional to build. Add CMake option `BUILD_STATIC_LIBS` to build static libs. This is useful for building a Conda package, since [Conda recipes should not build static libs for most use cases](https://github.com/conda-forge/cfep/blob/70f80e245a3497be35cbcf03df91d8b53b4e7931/cfep-18.md).
* Fix DLL loading for Python 3.8+ on Windows. See https://github.com/conda-forge/python-feedstock/issues/307
* Some CI plumbing. For some reason, Homebrew GCC fails `export_lib()` with a cryptic error, and I cannot reproduce on my machine. For now, the CI should just use Apple Clang. Some tests that are known to fail with Apple Clang are marked as XFAIL.

### CODE REVIEW

**Comment by hcho3** [comment]
@dovahcrow Would you be able to review this? Let me know if this PR is adequate for your Rust runtime.

**Comment by dovahcrow** [comment]
@hcho3 tbh I'm not very familiar with C++ and its build system. I can only confirm this is sufficient for building the rust runtime binding.

**Comment by hcho3** [comment]
Somehow the CI is unable to use Homebrew GCC :(  Why did the CI have to break at this time, when 1.0 is about to go out ;)

**Comment by dovahcrow** [comment]
> Somehow the CI is unable to use Homebrew GCC :( Why did the CI have to break at this time, when 1.0 is about to go out ;)

Just let me know if there's anything I can help with. 

I just finished nearly all the bindings of the runtime in Rust, except for reading `DMatrix` from file and CSR.

**Pull request merged**
