### PR TITLE
Fix segfault while loading xgboost binary models

### LINKED ISSUE #210: Segfault when loading model from XGBoost binary format
Treelite segfaults when attempting to load a model from XGBoost binary format, as demonstrated [here](https://travis-ci.org/github/dmlc/treelite/jobs/731657170#L4286) with [this test case](https://github.com/dmlc/treelite/pull/209/files#diff-0f916fd9e433ccfb1f3c25d79f350ca9R160-R162). I'm working on tracking down the exact circumstances under which this segfault is encountered and will update as I discover more.

### PR DESCRIPTION
**Pull request by wphicks**
Closes #210

### CODE REVIEW

**Comment by wphicks** [comment]
Backtrace:
```
#0  0x00007fffe7c4de9f in std::string::size (this=0x7fffffff6e68)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/bits/basic_string.h:3901
#1  std::string::append (this=0x7fffffff6cb0, __str=...)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:777
#2  0x00007fffcac0f16a in dmlc::io::LocalFileSystem::Open(dmlc::io::URI const&, char const*, bool) () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/site-packages/xgboost/lib/libxgboost.so
#3  0x00007fffe58ff7cb in dmlc::Stream::Create(char const*, char const*, bool) () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/site-packages/treelite/lib/libtreelite.so
#4  0x00007fffe58ba7b7 in treelite::frontend::LoadXGBoostModel(char const*, treelite::Model*) () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/site-packages/treelite/lib/libtreelite.so
#5  0x00007fffe5855015 in TreeliteLoadXGBoostModel () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/site-packages/treelite/lib/libtreelite.so
#6  0x00007ffff65ba9dd in ffi_call_unix64 () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/lib-dynload/../../libffi.so.7
#7  0x00007ffff65ba067 in ffi_call_int () from /home/whicks/anaconda3/envs/treelite_test/lib/python3.7/lib-dynload/../../libffi.so.7
#8  0x00007ffff65d2517 in _call_function_pointer (argcount=2, resmem=0x7fffffff71e0, restype=<optimized out>, atypes=0x7fffffff71a0, avalues=0x7fffffff71c0, pProc=0x7fffe5854fb0 <TreeliteLoadXGBoostModel>, 
    flags=4353) at /usr/local/src/conda/python-3.7.9/Modules/_ctypes/callproc.c:829
#9  _ctypes_callproc (pProc=0x7fffe5854fb0 <TreeliteLoadXGBoostModel>, argtuple=<optimized out>, flags=4353, argtypes=<optimized out>, restype=0x555555b8c740, checker=0x0)
    at /usr/local/src/conda/python-3.7.9/Modules/_ctypes/callproc.c:1201
#10 0x00007ffff65d2f84 in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=0x0) at /usr/local/src/conda/python-3.7.9/Modules/_ctypes/_ctypes.c:4025
#11 0x00005555556c0ccb in _PyObject_FastCallKeywords (callable=0x7fffca3c3ae0, stack=0x7fffca69bba0, nargs=2, kwnames=0x0) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:199
```

**Comment by hcho3** [comment]
@wphicks I've seen this issue before. Treelite and XGBoost both link with dmlc-core library, and they currently use incompatible versions.  Treelite should use commit 5df8305fe699d3b503d10c60a231ab0223142407 of dmlc-core, to match the version used by XGBoost.

**Comment by hcho3** [comment]
Change this line to 5df8305fe699d3b503d10c60a231ab0223142407:
https://github.com/dmlc/treelite/blob/5e9af4f8ce5eddcc55508f1d6757cae636d177f1/cmake/ExternalLibs.cmake#L6

**Comment by hcho3** [comment]
@wphicks Related issue: https://github.com/apache/incubator-tvm/issues/4953. This was fixed by https://github.com/dmlc/xgboost/pull/5590 by hiding all C++ symbols in `libxgboost.so`. It appears that the fix was not complete.

**Comment by wphicks** [comment]
The fix for the underlying problem will be addressed by [dmlc/xgboost#6188](https://github.com/dmlc/xgboost/pull/6188). I'll update this PR tomorrow with a workaround that avoids using dmlc's `LocalFileSystem` to access the file.

**Comment by hcho3** [comment]
Great! Here are the list of files that uses `dmlc::Stream::Create`:
```
$ grep -R dmlc::Stream::Create * --color -I
c_api/c_api.cc:  std::unique_ptr<dmlc::Stream> fo(dmlc::Stream::Create(path, "w"));
compiler/ast_native.cc:        dmlc::Stream::Create(param.annotate_in.c_str(), "r"));
frontend/xgboost.cc:  std::unique_ptr<dmlc::Stream> fi(dmlc::Stream::Create(filename, "r"));
frontend/xgboost_json.cc:  std::unique_ptr<dmlc::Stream> fi(dmlc::Stream::Create(filename, "r"));
frontend/lightgbm.cc:  std::unique_ptr<dmlc::Stream> fi(dmlc::Stream::Create(filename, "r"));
```
They should all be replaced with the standard C++ library functions for file I/O.

**Comment by wphicks** [comment]
This PR does not eliminate all uses of `dmlc::Stream::Create` since that would require changes to dmlc-core or more significant rewrites, but it eliminates the usage that causes #210 and which is preventing the merge of #202.

**Comment by wphicks** [comment]
Closing this out for now, since we're shifting over to xgboost 1.2.1rc1 to handle this instead. Will open a new PR with this approach.

**Pull request closed without merging**
