### PR TITLE
Add support for multiple data types

### PR DESCRIPTION
**Pull request by hcho3**
Addresses #95 and #111.

@trivialfis Your RTTI implementation in XGBoost JSON served as a great inspiration for this work. Thank you.

cc @canonizer @teju85

### CODE REVIEW

**Comment by hcho3** [comment]
Note: code coverage is broken.

**Comment by hcho3** [comment]
How to use the `Value` type:
```cpp
Value value;
switch (value.Type()) {
 case treelite::ADT::ValueImpl::ValueKind::kInt32:
  int32_t int32val = treelite::ADT::get<const treelite::ADT::Int32Value>(value);
  // ...
  break;
 case treelite::ADT::ValueImpl::ValueKind::kFloat32:
  float float32val = treelite::ADT::get<const treelite::ADT::Float32Value>(value);
  // ...
  break;
 case treelite::ADT::ValueImpl::ValueKind::kFloat64:
  double float64val = treelite::ADT::get<const treelite::ADT::Float64Value>(value);
      break;
 default:
  LOG(FATAL) << "Unknown value variant for field '" << name << "'";
}
```

**Comment by hcho3** [comment]
Need to also change generated lib to expose function interface with a different type.

**Comment by hcho3** [comment]
Now there are at least 4 different possible signatures for the prediction function:
```cpp
int predict(union Entry* data, int pred_margin);
double predict(union Entry* data, int pred_margin);
size_t predict(union Entry* data, int pred_margin, float* result);
size_t predict(union Entry* data, int pred_margin, double* result);
```

This is quickly getting out of control. We should introduce type-erased interface to reduce complexity.

**Comment by CJxD** [comment]
> Now there are at least 4 different possible signatures for the prediction function:
> 
> ```c++
> int predict(union Entry* data, int pred_margin);
> double predict(union Entry* data, int pred_margin);
> size_t predict(union Entry* data, int pred_margin, float* result);
> size_t predict(union Entry* data, int pred_margin, double* result);
> ```
> 
> This is quickly getting out of control. We should introduce type-erased interface to reduce complexity.

Indeed. I **strongly** recommended an 8-bit datatype in here too. For the sake of reducing model size by as much as 75% in compiled C code, I always run my C source through a post processor to convert all floats to uint8_t.

I was about to create a pull request that could intelligently determine the smallest data type that could successfully separate the branches of a tree, but this pull request has the potential.

**Comment by shashankg7** [comment]
Hi, 

Any plans to release this version anytime soon?

**Comment by simon19891101** [comment]
Hi there, may I know if this is merged? Just to say I'm still having the wrong predictions using the latest master https://github.com/dmlc/treelite/issues/222. Thanks!

**Comment by hcho3** [comment]
@simon19891101 Take a look at https://github.com/dmlc/treelite/pull/203

**Pull request closed without merging**
